### ISSUE TITLE
could not pull image when installed with helm v3

### ISSUE THREAD

**Issue by Ray-Eldath** [baetyl/baetyl-cloud#208]
install baetyl-cloud with `helm install baetyl-cloud ./scripts/charts/baetyl-cloud/` failed with events:

![image](https://user-images.githubusercontent.com/7938763/102984206-355a3c00-4548-11eb-8c79-c4ade92f57f0.png)

it's reported that the image doesn't exist.

currently I'm using aliyun's image speeder service.

**Comment by hannatao** [comment]
You should first build the docker image before using helm to deploy.
The build command is noted in scripts/charts/baetyl_cloud/values.yml
`docker build -t baetyl-cloud:local-build -f Dockerfile-local .`

You can also follow https://docs.baetyl.io/zh_CN/latest/develop/build.html to build the executable file or build the image.
