### ISSUE TITLE
快速安装报错

### ISSUE THREAD

**Issue by haowaiwai** [baetyl/baetyl-cloud#257]
```
 curl -d "{\"name\":\"demo-node\"}" -H "Content-Type: application/json" -X POST http://172.20.0.2:30004/v1/nodes
{"code":"UnknownError","message":"nodes.cloud.baetyl.io \"demo-node\" is forbidden: User \"system:serviceaccount:default:baetyl-cloud\" cannot get resource \"nodes\" in API group \"cloud.baetyl.io\" in the namespace \"baetyl-cloud\"","requestId":""}
```

**Comment by hannatao** [comment]
You can follow the install document [link to documents](https://docs.baetyl.io/zh_CN/latest/develop/install.html). 

Make sure your git version is the same, and I recommend to install in helm mode.

If the question still exists, please leave the git version and your installation mode.
