### ISSUE TITLE
failed to install edge node

### ISSUE THREAD

**Issue by wfchair** [baetyl/baetyl-cloud#278]
I'm installing baetyl-cloud according to https://docs.baetyl.io/zh_CN/latest/develop/install.html

curl -d "{\"name\":\"demo-node\"}" -H "Content-Type: application/json" -X POST http://0.0.0.0:30004/v1/nodes
{"code":"UnknownError","message":"Error 1054: Unknown column 'report_meta' in 'field list'","requestId":""}

**Comment by hannatao** [comment]
Make sure you have done 
`git reset --hard fd97c860be11a.` 
The master branch is unstable, only the specific git version works.

**Comment by wfchair** [comment]
Thanks. Why I didn't see baetyl-function pod running?

$ kubectl get pod -n baetyl-edge-system
NAME                             READY   STATUS    RESTARTS   AGE
baetyl-init-69685fc665-pr9gd     1/1     Running   0          5m30s
baetyl-core-57cc8fdfd6-fwwrg     1/1     Running   0          5m28s
baetyl-broker-77bdffdd8c-tddvh   1/1     Running   0          5m17s

**Comment by hannatao** [comment]
Function and rule now are not default when you create a node.
You should add it to sysApps when create a node.
For example:
`curl -d "{\"name\":\"demo-node\",\"sysApps\":[\"baetyl-function\"]}" -H "Content-Type: application/json" -X POST http://0.0.0.0:30004/v1/nodes`

**Comment by wfchair** [comment]
Thanks. you'd better add the above to the main readme.
How can I post a function? Would you be kind to give me an example?
# not sure whether it's ok to continue discussion by the issue thread.

**Comment by hannatao** [comment]
You can visit https://docs.baetyl.io/zh_CN/latest/_static/api.html for open API.
This document might be out-of-date，and you can visit https://cloud.baidu.com/doc/BIE/index.html for commercial use or add "Baetyl_" wechat to join the baetyl group.
