### ISSUE TITLE
关于新版本的api咨询

### ISSUE THREAD

**Issue by hongcaohu** [baetyl/baetyl-cloud#342]
您好，在阅读了2.2版本的文档和相关openapi后，自己在本地搭建运行起来了，自己有一些问题需要咨询一下：
1. 文档中支持edgexfoundry 完整服务的下发。经过自己家的实践，通过openapi应用接口 从baetyl-cloud端成功 下发了所有相关的服务，经查看 边缘baetyl端是每个服务创建了相应的pod在运行，这时候就遇到服务间的通讯问题。edgexfoundry官方是通过docker-compose来运行，服务间的通讯默认是通过 “容器服务名”+“端口” 来实现通讯的。在baetyl的边端运行就会出现服务之间访问问题。 (目前我采用的方式是 将所有edgex服务共享主机网络，都配置通过localhost来通讯，不是知否还有其他方式 ? )

2. v2.2版本发布说明中，“新增了对已部署应用的远程调试、远程日志查看的API定义”，请问下这个功能怎么使用，使用文档中没有相应的说明

非常感谢

**Comment by zxxf18** [comment]
1、通过baetyl下发的应用是以k3s/k8s下pod的形式运行起来的，baetyl在部署的时候会为每个应用创建一个对应的service，集群内服务间访问可以通过serviceName的形式进行；此外baetyl提供了官方的broker模块，你也可以通过mqtt协议，借助这个模块进行消息通信，broker的链接默认需要通过tls证书加密，证书会在应用部署后自动挂载进var/lib/baetyl/system/certs目录下，可以直接使用，你也可以在云端配置为用户名密码的形式；
2、开源代码中提供了大部分的远程调试和远程日志实现的相关代码，详见baetyl/baetyl项目的chain/ 、ami/kube/kube_exec.go等，但是启用这些功能还需要端云的长连接，现有开源版本的端云链接为http，所以你需要自行实现一套如ws的长连接，实现的接口端侧为plugin/link.go；baetyl-cloud云端为plugin/sync_link.go；主要实现消息分发和处理功能。这些功能你可以在百度公有云BIE智能边缘下先进行体验。内部的实现版本的开源还在持续推动中

**Comment by hongcaohu** [comment]
@zxxf18 感谢您在百忙之中给的细心回复

看到了下发应用成功后的确为每个应用创建了一个service，之前没注意到。但是有的服务还是启动失败，如edgex-core-data服务，原因在于服务启动时监听了edgex-core-data:48080，导致启动失败。

level=INFO ts=2021-08-11T06:00:23.977843473Z app=edgex-core-data source=registry.go:80 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=INFO ts=2021-08-11T06:00:24.000520988Z app=edgex-core-data source=database.go:147 msg="Database connected"
level=INFO ts=2021-08-11T06:00:24.011967025Z app=edgex-core-data source=database.go:112 msg="Database for V2 API connected"
level=INFO ts=2021-08-11T06:00:24.013682338Z app=edgex-core-data source=init.go:127 msg="Connected to zero Message Bus @ tcp://*:5563 publishing on 'events' topic"
level=INFO ts=2021-08-11T06:00:24.013712456Z app=edgex-core-data source=telemetry.go:86 msg="Telemetry starting"
level=INFO ts=2021-08-11T06:00:24.01393312Z app=edgex-core-data source=httpserver.go:99 msg="Web server starting (edgex-core-data:48080)"
level=INFO ts=2021-08-11T06:00:24.013953544Z app=edgex-core-data source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2021-08-11T06:00:24.037889904Z app=edgex-core-data source=message.go:51 msg="Starting edgex-core-data 1.3.1 "
level=INFO ts=2021-08-11T06:00:24.037940319Z app=edgex-core-data source=message.go:55 msg="This is the Core Data Microservice"
level=INFO ts=2021-08-11T06:00:24.037950632Z app=edgex-core-data source=message.go:58 msg="Service started in: 4.282532399s"
level=INFO ts=2021-08-11T06:00:24.039667333Z app=edgex-core-data source=httpserver.go:107 msg="Web server stopped"

在下发时env中 SERVICE_HOST 配置为 localhost时是可以启动成功，
  {
    "name": "SERVICE_HOST",
    "value": "localhost"
  }
但是localhost:48080会被注册到consul，而导致consul监测心跳会请求会失败。

附上我的创建应用的请求体：
[request.txt](https://github.com/baetyl/baetyl-cloud/files/6966269/request.txt)

最后请问 可以提供下发edgexfoundry 的服务的请求体例子吗？

非常感谢

**Comment by hongcaohu** [comment]
@zxxf18 原因应该是，在下发service时 已经配置了hostname，但是在baetyl边端对应服务的pod里 hostname没有生效，请问我的配置哪里有问题吗？

**Comment by hongcaohu** [comment]
上述问题已经解决，服务启动在0.0.0.0

**Comment by zhangtag** [comment]
按照您的请求体部署edgex后，也遇到了服务启动错误的情况，如果可以的话，烦请您告知一下您部署成功的请求体。谢谢😭
