### ISSUE TITLE
mariadb always pending, how to fix?

### ISSUE THREAD

**Issue by Haoyuli1990** [baetyl/baetyl-cloud#424]
![image](https://user-images.githubusercontent.com/81141382/148006185-c64b6313-12ec-4ea5-a316-4ea108cdd9e5.png)
![image](https://user-images.githubusercontent.com/81141382/148006289-b142623a-129c-475c-9587-8c70bfbbec90.png)
![image](https://user-images.githubusercontent.com/81141382/148006342-1de607e0-2e4d-43bb-b8f4-08f8b32c3993.png)
it seems no pv.

**Comment by hannatao** [comment]
mariadb非baetyl的必须依赖项，你也可以选择尝试安装mysql。

**Comment by zhangtag** [comment]
我也遇到这个问题。我还以为是自己的部署问题

**Comment by zhangtag** [comment]
处于pending状态是因为该pvc没有空闲的pv可以挂载。新建yaml文件
```shell
# filename:masetr-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
      name: mariadb-master
      labels:
        app: mariadb
spec:
 capacity:
  storage: 8Gi
 accessModes:
    - ReadWriteOnce
 hostPath:
  path: /opt/mariadb-master
```
通过以下命令创建pv并获取权限
```shell
kubectl create -f masetr-pv.yaml.yaml    # 创建
chown 1001:root /opt/mariadb-master   #启动后查看pod容器日志，提示没权限创建目录或初始化失败，需要修改宿主目录的权限为1001，因为容器默认以1001的用户启动
```
稍等一会然后查看状态，基本上就已经在running了
```shell
kubectl get pods
kubectl get pv
kubectl get pvc
```
