### ISSUE TITLE
边缘节点部署失败

### ISSUE THREAD

**Issue by clh-cod** [baetyl/baetyl-cloud#51]
依照文档的k8s安装过程，
云边分别部署在两台机器上，创建好节点后，在边缘端部署失败，请问是什么原因
![2](https://user-images.githubusercontent.com/69289383/89885217-4c356d00-dbfd-11ea-94cb-b9794c2919e2.PNG)

**Comment by allen-lj** [comment]
> 我云边分别部署在两台机器上，创建好节点后，在边缘端部署失败，请问是什么原因
> ![2](https://user-images.githubusercontent.com/69289383/89885217-4c356d00-dbfd-11ea-94cb-b9794c2919e2.PNG)
可以使用 kubectl logs baetyl-init-67c5bd4f44-2rkxn -n baetyl-edge-system 和kubectl describe po baetyl-init-67c5bd4f44-2rkxn -n baetyl-edge-system 查看一下日志

**Comment by clh-cod** [comment]
@allen-lj 
{"level":"info","ts":1597201880.1413596,"caller":"ami/ami.go:64","msg":"ami generator registered","generator":"kubernetes"}
Version:      v2.0.0
Git revision: git-9ac3721
Go version:   go1.13.5
{"level":"debug","ts":1597201880.141942,"caller":"context/context.go:123","msg":"context is created","file":"etc/baetyl/service.yml","conf":{"http":{"address":"http://baetyl-function:80","timeout":30000000000,"keepalive":30000000000,"maxIdleConns":100,"idleConnTimeout":90000000000,"tlsHandshakeTimeout":10000000000,"expectContinueTimeout":1000000000,"ca":"","key":"","cert":"","name":"","insecureSkipVerify":false},"mqtt":{"address":"tcp://baetyl-broker:1883","username":"","password":"","clientid":"","cleansession":false,"timeout":30000000000,"keepalive":30000000000,"maxReconnectInterval":180000000000,"maxCacheMessages":10,"disableAutoAck":false,"subscriptions":[],"ca":"","key":"","cert":"","name":"","insecureSkipVerify":false},"logger":{"level":"debug","encoding":"json","filename":"var/log/baetyl/service.log","compress":false,"maxAge":15,"maxSize":50,"maxBackups":15}}}
{"level":"info","ts":1597201880.1444983,"caller":"context/run.go:34","msg":"service starting","args":["baetyl-init"],"pwd":"/"}
{"level":"info","ts":1597201880.160453,"caller":"initz/main.go:131","msg":"collect and report stats to cloud","init":"sync"}
{"level":"warn","ts":1597201880.1927075,"caller":"ami/kube_collect.go:142","msg":"failed to collect pod metrics","ami":"kube","error":"podmetrics.metrics.k8s.io \"baetyl-edge-system/baetyl-init-55c8456c55-tqbm4\" not found"}
{"level":"debug","ts":1597201880.193024,"caller":"sync/sync.go:96","msg":"sync reports cloud shadow","core":"sync","report":"{\"node\":{\"hostname\":\"node1\",\"address\":\"192.168.203.135\",\"arch\":\"amd64\",\"kernelVer\":\"3.10.0-1127.el7.x86_64\",\"os\":\"linux\",\"containerRuntime\":\"docker://19.3.9\",\"machineID\":\"a6158cd59fbf43729d25d3fc713f608d\",\"bootID\":\"fc35b050-90d8-482d-bbbc-6afcc9f92fda\",\"systemUUID\":\"B77F4D56-816B-9C51-1113-EE1169E98388\",\"osImage\":\"CentOS Linux 7 (Core)\"},\"nodestats\":{\"usage\":{\"cpu\":\"101000545n\",\"memory\":\"1326596Ki\"},\"capacity\":{\"cpu\":\"1\",\"memory\":\"1863012Ki\"}},\"sysapps\":[{\"name\":\"baetyl-init\"}],\"sysappstats\":[{\"name\":\"baetyl-init\",\"status\":\"Pending\",\"instances\":{\"baetyl-init-55c8456c55-tqbm4\":{\"name\":\"baetyl-init-55c8456c55-tqbm4\",\"serviceName\":\"baetyl-init\",\"status\":\"Pending\",\"createTime\":\"2020-08-12T03:09:31Z\"}}}],\"time\":\"2020-08-12T03:11:20.192755791Z\"}"}
{"level":"error","ts":1597201880.1961174,"caller":"initz/main.go:105","msg":"failed to report app info","init":"sync","error":"Post https://192.168.203.135:30005/v1/sync/report: remote error: tls: bad certificate","errorVerbose":"Post https://192.168.203.135:30005/v1/sync/report: remote error: tls: bad certificate\ngithub.com/baetyl/baetyl-go/errors.Trace\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/errors/error.go:33\ngithub.com/baetyl/baetyl-go/http.(*Client).PostJSON\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/http/client.go:67\ngithub.com/baetyl/baetyl/sync.(*sync).Report\n\t/go/src/sync/sync.go:97\nmain.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:103\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"main.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:105\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1597201880.1963081,"caller":"context/run.go:37","msg":"service has stopped with error","error":"system application baetyl-core is required for connection with cloud","errorVerbose":"system application baetyl-core is required for connection with cloud\ngithub.com/baetyl/baetyl-go/errors.Trace\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/errors/error.go:33\nmain.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:106\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:37\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by clh-cod** [comment]
@allen-lj 
{"level":"info","ts":1597201880.1413596,"caller":"ami/ami.go:64","msg":"ami generator registered","generator":"kubernetes"}
Version:      v2.0.0
Git revision: git-9ac3721
Go version:   go1.13.5
{"level":"debug","ts":1597201880.141942,"caller":"context/context.go:123","msg":"context is created","file":"etc/baetyl/service.yml","conf":{"http":{"address":"http://baetyl-function:80","timeout":30000000000,"keepalive":30000000000,"maxIdleConns":100,"idleConnTimeout":90000000000,"tlsHandshakeTimeout":10000000000,"expectContinueTimeout":1000000000,"ca":"","key":"","cert":"","name":"","insecureSkipVerify":false},"mqtt":{"address":"tcp://baetyl-broker:1883","username":"","password":"","clientid":"","cleansession":false,"timeout":30000000000,"keepalive":30000000000,"maxReconnectInterval":180000000000,"maxCacheMessages":10,"disableAutoAck":false,"subscriptions":[],"ca":"","key":"","cert":"","name":"","insecureSkipVerify":false},"logger":{"level":"debug","encoding":"json","filename":"var/log/baetyl/service.log","compress":false,"maxAge":15,"maxSize":50,"maxBackups":15}}}
{"level":"info","ts":1597201880.1444983,"caller":"context/run.go:34","msg":"service starting","args":["baetyl-init"],"pwd":"/"}
{"level":"info","ts":1597201880.160453,"caller":"initz/main.go:131","msg":"collect and report stats to cloud","init":"sync"}
{"level":"warn","ts":1597201880.1927075,"caller":"ami/kube_collect.go:142","msg":"failed to collect pod metrics","ami":"kube","error":"podmetrics.metrics.k8s.io \"baetyl-edge-system/baetyl-init-55c8456c55-tqbm4\" not found"}
{"level":"debug","ts":1597201880.193024,"caller":"sync/sync.go:96","msg":"sync reports cloud shadow","core":"sync","report":"{\"node\":{\"hostname\":\"node1\",\"address\":\"192.168.203.135\",\"arch\":\"amd64\",\"kernelVer\":\"3.10.0-1127.el7.x86_64\",\"os\":\"linux\",\"containerRuntime\":\"docker://19.3.9\",\"machineID\":\"a6158cd59fbf43729d25d3fc713f608d\",\"bootID\":\"fc35b050-90d8-482d-bbbc-6afcc9f92fda\",\"systemUUID\":\"B77F4D56-816B-9C51-1113-EE1169E98388\",\"osImage\":\"CentOS Linux 7 (Core)\"},\"nodestats\":{\"usage\":{\"cpu\":\"101000545n\",\"memory\":\"1326596Ki\"},\"capacity\":{\"cpu\":\"1\",\"memory\":\"1863012Ki\"}},\"sysapps\":[{\"name\":\"baetyl-init\"}],\"sysappstats\":[{\"name\":\"baetyl-init\",\"status\":\"Pending\",\"instances\":{\"baetyl-init-55c8456c55-tqbm4\":{\"name\":\"baetyl-init-55c8456c55-tqbm4\",\"serviceName\":\"baetyl-init\",\"status\":\"Pending\",\"createTime\":\"2020-08-12T03:09:31Z\"}}}],\"time\":\"2020-08-12T03:11:20.192755791Z\"}"}
{"level":"error","ts":1597201880.1961174,"caller":"initz/main.go:105","msg":"failed to report app info","init":"sync","error":"Post https://192.168.203.135:30005/v1/sync/report: remote error: tls: bad certificate","errorVerbose":"Post https://192.168.203.135:30005/v1/sync/report: remote error: tls: bad certificate\ngithub.com/baetyl/baetyl-go/errors.Trace\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/errors/error.go:33\ngithub.com/baetyl/baetyl-go/http.(*Client).PostJSON\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/http/client.go:67\ngithub.com/baetyl/baetyl/sync.(*sync).Report\n\t/go/src/sync/sync.go:97\nmain.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:103\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"main.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:105\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1597201880.1963081,"caller":"context/run.go:37","msg":"service has stopped with error","error":"system application baetyl-core is required for connection with cloud","errorVerbose":"system application baetyl-core is required for connection with cloud\ngithub.com/baetyl/baetyl-go/errors.Trace\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/errors/error.go:33\nmain.(*core).reportAndDesireCloud\n\t/go/src/cmd/initz/main.go:106\nmain.main.func1\n\t/go/src/cmd/initz/main.go:132\ngithub.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:35\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/baetyl/baetyl-go/context.Run\n\t/go/pkg/mod/github.com/baetyl/baetyl-go@v0.1.90/context/run.go:37\nmain.main\n\t/go/src/cmd/initz/main.go:124\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by allen-lj** [comment]
@clh-cod 
把`baetyl_certificate` 这个表数据清空，重新使用https://github.com/baetyl/baetyl-cloud/blob/master/scripts/sql/data.sql里的数据导入

**Comment by clh-cod** [comment]
@allen-lj 已解决，谢谢帮忙
