### ISSUE TITLE
升级baetyl cloud版本后，数据库数据如何迁移？

### ISSUE THREAD

**Issue by benjaminlinken** [baetyl/baetyl-cloud#524]
您好，当从旧版本baetyl cloud升级到最新的版本，数据库表单也发生了变换（此时数据库里存在旧的数据），要怎么实现数据迁移来完成版本升级？

**Comment by hannatao** [comment]
要看你这边是从哪个版本升级过来的，可以通过git记录查看mysql建表语句的变更，然后整理出数据库字段的变更进行数据库表的alter

**Comment by benjaminlinken** [comment]
@hannatao 但是数据库表单迁移应该是和代码逻辑强相关的吧，目前是否会出现低版本由于数据兼容问题无法升级至高版本的问题？

**Comment by hannatao** [comment]
我们在数据库变更时，考虑了兼容问题，基本都是新增字段，不会修改已有字段。

**Comment by benjaminlinken** [comment]
@hannatao 多谢解答！
