### ISSUE TITLE
是不是可以增加关于	kubeConfig.QPS  	kubeConfig.Burst 的配置选项

### ISSUE THREAD

**Issue by garfcat** [baetyl/baetyl-cloud#583]
我看代码目前这两个配置都是使用的默认值，QPS 为 5  ，Burst 为 10，接入几台设备就能达到这个限流，所以是否可以在cloud 的配置中添加关于这两个的配置项。

**Comment by hannatao** [comment]
这个暂时还没有支持的计划，欢迎实现提交。
