### ISSUE TITLE
namespace 是否可以暴露给接口？

### ISSUE THREAD

**Issue by garfcat** [baetyl/baetyl-cloud#584]
现在namespace 应该只能设置一个，可否暴漏给接口，可以在接口中指定在哪个namespace 中创建/获取配置呢，这样的话一个cloud 可以做到不同项目或者用户的资源隔离。

**Comment by hannatao** [comment]
这个是需要去实现plugin/default/auth中的接口就可以，是通过用户登录信息去set namespace的。
