### ISSUE TITLE
how to get edgenode system logs and app logs

### ISSUE THREAD

**Issue by HelloZCB** [baetyl/baetyl-cloud#67]
For now, baetyl-cloud can only get edge node status and container app status. How can baetyl-cloud collect edge nodes system logs and container app logs?

**Comment by allen-lj** [comment]
> For now, baetyl-cloud can only get edge node status and container app status. How can baetyl-cloud collect edge nodes system logs and container app logs?
@HelloZCB we have not yet plan to collect system logs and container app logs of  edge nodes in baetyl-cloud, you can use filebeat or other middleware to collect logs.
We are developing the SSH function in the Commercial Edition. In this edition, you can SSH into the edge container via baetyl-cloud.
